version: "3.9"

services:
  api:
    image: yesha999/uer_yug:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
    ports:
      - 10480:10480
    volumes:
      - ./.env:/app/.env